name: picter-app-backend
description: App Description
ignoreFiles: .git node_modules yarn.lock db.sql 
modules:
- name: template
  language: nodejs16.x
  web: express
  description: Module description
  functions:
  - name: entry
    entry: entry.js
    description: the entry point for the function